arrayName = {
    'Part1_Item1_ApplicationType': ['FirstTime','ReApply'],
    'Part1_Item2_GrantedTPS': ['U','I'],
    'Part1_Item3_EADApp': ['Yes','No'],
    'Part1_TPScountry': 'CountryApplyingAsylum',

    # Personal Information
    'Part2_Item1_FamilyName': 'Surname',
    'Part2_Item1_GivenName': 'FirstName',
    'Part2_Item1_MiddleName': 'MiddleName',
    'Part2_Item3_FamilyName': 'OtherSurname',
    'Part2_Item3_GivenName': 'OtherFirstName',
    'Part2_Item3_MiddleName': 'OtherMiddleName',
    'Part2_Item2_FamilyName': 'OtherSurname',
    'Part2_Item2_GivenName': 'OtherFirstName',
    'Part2_Item2_MiddleName': 'OtherMiddleName',
    'Part2_Item4_InCareofName': 'InCareOfName',
    'Part2_Item4_StreetNumberName': 'MailingStreetName',
    'Part2_Item4_Unit': 'MailingApartment', # ['Apt','Ste','Flr'],
    'Part2_Item4_AptSteFlrNumber': 'MailingApartmentNumber',
    'Part2_Item4_CityOrTown': 'MailingCity',
    'Part2_Item4_State': 'MailingState',
    'Part2_Item4_ZipCode': 'MailingZipCode',
    'Part2_Item5_YN': 'IsMailingAddressSame',# ['Yes','No'],
    'Part2_Item6_StreetNumberName': 'PhysicalStreetName',
    'Part2_Item6_Unit': 'PhysicalApartment',# ['Apt','Ste','Flr'],
    'Part2_Item6_AptSteFlrNumber': 'PhysicalApartmentNumber',
    'Part2_Item6_CityOrTown': 'PhysicalCity',
    'Part2_Item6_State': 'PhysicalState',
    'Part2_Item6_ZipCode': 'PhysicalZipCode',
    'Part2_Item7_AlienNumber': 'AlienNumber',
    'Part2_Item8_AcctIdentifier': 'USCISAccountNumber',
    'Part2_Item9_SocialSecurityNumber': 'SocialSecurityNumber',
    'Part2_Item10_DateOfBirth': 'DateOfBirth',
    'Part2_Item11_DateOfBirth': 'OtherDatesOfBirth',# ['DateOfBirth','DateOfBirth'],
    'Part2_Item12_Gender': 'Gender',# ['Male','Female'],
    'Part2_Item13_CityOrTown': 'CityOfBirth',
    'Part2_Item14_CountryofBirth': 'CountryOfBirth',
    'Part2_Item15': 'countryOfResidence', # ['a','b','c','d'],
    'Part2_Item16': 'countryOfNationality', # ['a','b','c','d'],
    'Part2_Item17_MaritalStatus': 'MaritalStatus',# ['Single','Married','Divorced','Widowed','Separated','Other','Unknown'],
    'Part2_Item17_MaritalStatusOther': 'MaritalDate',

    # Immigration
    'P2_Line7_DateOfBirth': "DateOfEntry",
    'Part2_Item19_ImmigrationStatus': 'ImmigrationStatus',
    'Part2_Item20_PortofEntry': 'EntryPort',
    'Part2_Item20_CityOrTown': 'EntryCity',
    'Part2_Item20_State': 'EntryState',
    'Part2_Item22_I94': 'I94Number',
    'Part2_Item21_AuthorizedPdofStay': 'PeriodOfStay',
    'Part2_Item22_Passport': 'PassportNumber',
    'Part2_Item22_Passport': 'TravelDocumentNumber',
    'Part2_Item23a_AddlPassport': 'AdditionalPassport', # ['a', 'b'],
    'Part2_Item24_CountryofIssuance': 'CountryOfIssuance',
    'Part2_Item24_PassportExpiration': 'PassportExpirationDate',
    'Part2_Item25_ImmigrationStatus': 'CurrentStatus',
    'Part2_Item25_ImmigrationProceedings': ['Yes','No'],
    'Part2_Item27_ProceedingType': ['Type 1','Type 2','Type 3'],
    'Part2_Item28_LocDOJProceedings': 'DOJLocation',
    'Part2_Item29_LocFedCtProceedings': 'FederalCourtLocation',
    'Part2_Item31a_ProceedingDateFrom': 'DateFrom',
    'Part2_Item31b_ProceedingDateTo': 'DateTo',
    'Part2_Item31e_Present': ['Present'],
    'Part3_Item1_Ethnicity': ['Hispanic or Latino','Not Hispanic or Latino'],
    'Part3_Item2_Race': ['W','W','B','I','H'],
    'Part3_Item5_Eyecolor': ['Black','Blue','Brown','Gray','Green','Hazel','Maroon','Pink','Unknown/Other'],
    'Part3_Item6_Haircolor': ['Bald','Black','Blonde','Brown','Gray','Red','Sandy','White','Unknown/Other'],
    'Pt2Line3_HeightFeet': 'Feet',
    'Pt2Line3_HeightInches': 'Inch',
    'Pt2Line4_HeightInches': ['2','1','3'],

    # Current Spouse
    'Part4_Item1_USCISNumber': 'SpouseUSCISAccountNumber',
    'Part4_Item2_AlienNumber': 'SpouseAlienNumber',
    'Part4_Item3_FamilyName': 'SpouseSurname',
    'Part4_Item3_GivenName': 'SpouseFirstName',
    'Part4_Item3_MiddleName': 'SpouseMiddleName',
    'Part4_Item4_StreetNumberName': 'SpouseStreetName',
    'Part4_Item4_Unit': ['Apt','Ste','Flr'],
    'Part4_Item4_AptSteFlrNumber': 'ApartmentNumber',
    'Part4_Item4_CityOrTown': 'City',
    'Part4_Item4_State': 'State',
    'Part4_Item4_ZipCode': 'ZipCode',
    'Part4_Item4_Province': 'Province',
    'Part4_Item4_PostalCode': 'PostalCode',
    'Part4_Item4_Country': 'Country',
    'Part4_Item5_DateOfBirth': 'DateOfBirth',
    'Part4_Item6_DateOfMarriage': 'DateOfMarriage',
    'Part4_Item7_PlaceofMarriage': 'PlaceOfMarriage',
    'Part4_Item8_CityOrTown': 'City',
    'Part4_Item8_Province': 'Province',
    'Part4_Item8_State': 'State',
    'Part4_Item8_Country': 'Country',
    'Part4_Item9_TPS': ['Y','N'],
    'Part4_Item10b_DateFrom': 'DateFrom',
    'Part4_Item10c_DateTo': 'DateTo',
    'Part4_Item10d_Present': 'Present',
    'Part4_Item10e_IDK': 'I don\'t know',
    'Part5_Item1_FamilyName': 'Surname',
    'Part5_Item1_GivenName': 'FirstName',
    'Part5_Item1_MiddleName': 'MiddleName',
    'Part5_Item2_FSpouseNationalities': 'Nationality',
    'Part5_Item3_AlienNumber': 'AlienNumber',
    'Part5_Item4_FSpouseDOB': 'DateOfBirth',
    'Part5_Item5_FSpouseDOD': 'DateOfDeceased',
    'Part5_Item6_MarriageFrom': 'DateFrom',
    'Part5_Item6_MarriageTo': 'DateTo',
    'Part5_Item7_MarriageEnded': 'HowMarriageEnded',
    'Part5_Item8_YDI': ['Yes','No','Don\'t know'],
    'Part5_Item9a_DateFrom': 'DateFrom',
    'Part5_Item9b_DateTo': 'DateTo',
    'Part5_Item9c_Present': 'Present',
    'Part5_Item9d_IDK': 'I don\'t know',
    'Part5_Item10_YNI': ['Yes','No','I don\'t know'],
    'Part5_Item11_FamilyName': 'Surname',
    'Part5_Item11_GivenName': 'FirstName',
    'Part5_Item11_MiddleName': 'MiddleName',
    'Part5_Item12_FSpouseNationalities': 'Nationality',
    'Part5_Item13_AlienNumber': 'AlienNumber',
    'Part5_Item14_FSpouseDOB': 'DateOfBirth',
    'Part5_Item15_FSpouseDOD': 'DateOfDecease',
    'Part5_Item16_MarriageFrom': 'DateFrom',
    'Part5_Item16_MarriageTo': 'DateTo',
    'Part5_Item17_MarriageEnded': 'HowMarriageEnded',
    'Part5_Item18_YNI': ['Yes','No', 'I don\'t know'],
    'Part5_Item19a_DateFrom': 'DateFrom',
    'Part5_Item19b_DateTo': 'DateTo',
    'Part5_Item19c_Present': 'Present',
    'Part5_Item19d_IDK': 'I don\'t know',
    'Part5_Item20_YNI': ['Yes','No','I don\'t know'],
    'Part6_Item1_FamilyName': 'Surname',
    'Part6_Item1_GivenName': 'FirstName',
    'Part6_Item1_MiddleName': 'MiddleName',
    'Part6_Item2_USCISNumber': 'USCISAccountNumber',
    'Part6_Item3_AlienNumber': 'AlienNumber',
    'Part6_Item4_DateOfBirth': 'DateOfBirth',
    'Part6_Item5_StreetNumberName': 'StreetNumber',
    'Part6_Item5_Unit': ['Apt', 'Ste', 'Flr'],
    'Part6_Item5_AptSteFlrNumber': 'ApartmentNumber',
    'Part6_Item5_CityOrTown': 'City',
    'Part6_Item5_State': 'State',
    'Part6_Item5_ZipCode': 'ZipCode',
    'Part6_Item5_Province': 'Province',
    'Part6_Item5_PostalCode': 'PostalCode',
    'Part6_Item5_Country': 'Country',
    'Part6_Item6_ChildTPSFrom': 'DateFrom',
    'Part6_Item6_ChildTPSTo': 'DateTo',
    'Part6_Item8_FamilyName': 'Surname',
    'Part6_Item8_GivenName': 'FirstName',
    'Part6_Item8_MiddleName': 'MiddleName',
    'Part6_Item10_AlienNumber': 'AlienNumber',
    'Part6_Item11_DateOfBirth': 'DateOfBirth',
    'Part6_Item12_StreetNumberName': 'StreetNumber',
    'Part6_Item12_Unit': ['Apt','Ste','Flr'],
    'Part6_Item12_AptSteFlrNumber': 'ApartmentNumber',
    'Part6_Item12_CityOrTown': 'City',
    'Part6_Item12_State': 'State',
    'Part6_Item12_Province': 'Province',
    'Part6_Item12_ZipCode': 'ZipCode',
    'Part6_Item12_Province': 'Province',
    'Part6_Item12_PostalCode': 'PostalCode',
    'Part6_Item12_Country': 'Country',
    'Part6_Item13_ChildTPSFrom': 'DateFrom',
    'Part6_Item12_ChildTPSTo': 'DateTo',
    'Part6_Item14_ChildAppTPS': ['Yes','No'],

    # Eligibility
    'Part7_Item1_CountryResidence': 'CountryOfNationality',
    'Part7_Item1_EnterUS': 'Yes',
    'Part7_Item1_Travel': ['Yes','No'],
    'Part7_Item2_CountriesTraveled': 'Country',
    'Part7_Item2_CountriesTraveledFrom': 'CountryDateFrom',
    'Part7_Item2_CountriesTraveledTo': 'CountryDateTo',
    'Part7_Item2_ImmigrationStatus': 'CountryImmigrationStatus',
    'Part7_Item2_ImmigrationOffer': ['Yes','No'],
    'Part7_Item2_DescribeCountries': 'CountryImmigrationDescription',
    'Part7_Item2_DidNotAccept': ['Yes','No'],
    'Part7_Item4a_YN': ['Yes','No'],
    'Part7_Item4b_YN': ['Yes','No'],
    'Part7_Item4c_YN': ['Yes','No'],
    'Part7_Item5a_YN': ['Yes','No'],
    'Part7_Item5b_YN': ['Yes','No'],
    'Part7_Item5c_YN': ['Yes','No'],
    'Part7_Item7a_YN': ['Yes','No'],
    'Part7_Item7b_YN': ['Yes','No'],
    'Part7_Item7c_YN': ['Yes','No'],
    'Part7_Item8_YN': ['Yes','No'],
    'Part7_Item9a_YN': ['Yes','No'],
    'Part7_Item9b_YN': ['Yes','No'],
    'Part7_Item9c_YN': ['Yes','No'],
    'Part7_Item9d_YN': ['Yes','No'],
    'Part7_Item9e_YN': ['Yes','No'],
    'Part7_Item11a_YN': ['Yes','No'],
    'Part7_Item11b_YN': ['Yes','No'],
    'Part7_Item11c_YN': ['Yes','No'],
    'Part7_Item11d_YN': ['Yes','No'],
    'Part7_Item12a_YN': ['Yes','No'],
    'Part7_Item12b_YN': ['Yes','No'],
    'Part7_Item12c_YN': ['Yes','No'],
    'Part7_Item12d_YN': ['Yes','No'],
    'Part7_Item13a_YN': ['Yes','No'],
    'Part7_Item13b_YN': ['Yes','No'],
    'Part7_Item13c_YN': ['Yes','No'],
    'Part7_Item17_YN': ['Yes','No'],
    'Part7_Item18a_YN': ['Yes','No'],
    'Part7_Item18b_YN': ['Yes','No'],
    'Part7_Item18c_YN': ['Yes','No'],
    'Part7_Item18d_YND': ['Yes','No'],
    'Part7_Item18e_YND': ['Yes','No','Don\'t know'],
    'Part7_Item19_YND': ['Yes','No'],
    'Part7_Item20_YND': ['Yes','No'],
    'Part7_Item21a_YND': ['Yes','No'],
    'Part7_Item21b_YND': ['Yes','No'],
    'Part7_Item21c_YND': ['Yes','No'],
    'Part7_Item22_YND': ['Yes','No'],
    'Part7_Item23_YND': ['Yes','No'],
    'Part7_Item24_YND': ['Yes','No'],
    'Part7_Item25_YND': ['Yes','No'],
    'Part7_Item26_YND': ['Yes','No'],
    'Part7_Item16c_YN': ['Yes','No'],
    'Part7_Item16b_YN': ['Yes','No'],
    'Part7_Item27_YND': ['Yes','No'],
    'Part7_Item29a_YN': ['Yes','No'],
    'Part7_Item29b_YN': ['Yes','No'],
    'Part7_Item29c_YN': ['Yes','No'],
    'Part7_Item29d_YN': ['Yes','No'],
    'Part7_Item29e_YN': ['Yes','No'],
    'Part7_Item14_YN': ['Yes','No'],
    'Part7_Item15_YN': ['Yes','No'],
    'Part7_Item16a_YN': ['Yes','No'],
    'Part7_Item31a_YN': ['Yes','No'],
    'Part7_Item31b_YN': ['Yes','No'],
    'Part7_Item32_YN': ['Yes','No'],
    'Part7_Item33_YN': ['Yes','No'],
    'Part7_Item34_YN': ['Yes','No'],
    'Part7_Item35_YN': ['Yes','No'],
    'Part7_Item36_YN': ['Yes','No'],
    'Part7_Item37a_YN': ['Yes','No'],
    'Part7_Item37b_YN': ['Yes','No'],
    'Part7_Item38a_YN': ['Yes','No'],
    'Part7_Item38b_YN': ['Yes','No'],
    'Part7_Item38c_YN': ['Yes','No'],
    'Part7_Item38d_YN': ['Yes','No'],
    'Part7_Item38e_YN': ['Yes','No'],
    'Part7_Item39a_YN': ['Yes','No'],
    'Part7_Item39b_YN': ['Yes','No'],
    'Part7_Item40a_YN': ['Yes','No'],
    'Part7_Item41_YN': ['Yes','No'],
    'Part8_Item1_AppStmt[0]': 'CanReadAndUnderstand',
    'Part8_Item1_AppStmt[1]': 'HasInterpreter',
    'Part8_Item1_Language': 'Language',
    'Part8_Item2_Preparer': 'HasPreparer',
    'Part8_Item2_PrepName': 'PreparerName',

    # Interpreter Information
    'Part9_Item1_FamilyName': 'InterpreterSurname',
    'Part9_Item1_GivenName': 'InterpreterFirstName',
    'Part9_Item2_OrgName': 'InterpreterOrganizationName',
    'Part9_Item3_StreetNumberName': 'InterpreterStreetName',
    'Part9_Item3_Unit': 'InterpreterApt', # ['Apt','Ste','Flr'],
    'Part9_Item3_AptSteFlrNumber': 'InterpreterApartmentNumber',
    'Part9_Item3_CityOrTown': 'InterpreterCity',
    'Part9_Item3_State': 'InterpreterState',
    'Part9_Item3_ZipCode': 'InterpreterZipCode',
    'Part9_Item3_Province': 'InterpreterProvince',
    'Part9_Item3_PostalCode': 'InterpreterPostalCode',
    'Part9_Item3_Country': 'InterpreterCountry',

    # Applicant
    'Part8_Item5_Email': 'ApplicantEmailAddress',
    'Part8_Item3_DayPhone': 'ApplicantDayPhoneNumber',
    'Part8_Item4_MobilePhone': 'ApplicantMobilePhoneNumber',
    'Part8_Item6a_Signature': 'ApplicantSignature',
    'Part8_Item6b_DateofSignature': 'DateOfSignature',

    # Interpreter
    'Part9_Item5_Email': 'InterpreterEmailAddress',
    'Part9_Item4_DaytimePhone': 'InterpreterDayPhoneNumber',
    'Part10_Item5_MobilePhone': 'InterpreterMobilePhoneNumber',
    'Part9_Item6_Signature': 'InterpreterSignature',
    'Part9_Item6_DateofSignature': 'InterpreterDateOfSignature',

    # Preparer Information
    'Part10_Item1_FamilyName': 'PreparerSurname',
    'Part10_Item1_GivenName': 'PreparerFirstName',
    'Part10_Item2_OrgName': 'PreparerOrganizationName',
    'Part10_Item3_StreetNumberName': 'PreparerStreetName',
    'Part10_Item3_Unit': 'PreparerApt', # ['Apt','Ste','Flr'],
    'Part10_Item3_AptSteFlrNumber': 'PreparerApartmentNumber',
    'Part10_Item3_CityOrTown': 'PreparerCity',
    'Part10_Item3_State': 'PreparerState',
    'Part10_Item3_ZipCode': 'PreparerZipCode',
    'Part10_Item3_Province': 'PreparerProvince',
    'Part10_Item3_PostalCode': 'PreparerPostalCode',
    'Part10_Item3_Country': 'PreparerCountry',
    'Part10_Item7_PreparerStmt': ['NotAttorney','Attorney'],
    'Part10_Item7b_Extend': ['Extend','NotExtend'],
    'Part10_Item8a_Signature': 'PreparerSignature',
    'Part10_Item8b_DateofSignature': 'PreparerDateOfSignature',
    'Part10_Item4_DaytimePhone': 'PreparerDayPhoneNumber',
    'Part10_Item5_MobilePhone': 'PreparerPhoneNumber',
    'Part10_Item6_Email': 'PreparerEmailAddress',

    # Additional Information
    'Part2_Item1_FamilyName': 'Surname',
    'Part2_Item1_GivenName': 'FirstName',
    'Part2_Item1_MiddleName': 'MiddleName',
    'AI_3a_PageNumber': 'PageNumber',
    'AI_3b_PartNumber': 'PartNumber',
    'AI_3c_ItemNumber': 'ItemNumber',
    'AI_3d_AdditionalInfo': 'AdditionalInformation',
    'AI_4a_PageNumber': 'PageNumber',
    'AI_4b_PartNumber': 'PartNumber',
    'AI_4c_ItemNumber': 'ItemNumber',
    'AI_4d_AdditionalInfo': 'AdditionalInformation',
    'AI_5a_PageNumber': 'PageNumber',
    'AI_5b_PartNumber': 'PartNumber',
    'AI_5c_ItemNumber': 'ItemNumber',
    'AI_5d_AdditionalInfo': 'AdditionalInformation',
    'AI_6a_PageNumber': 'PageNumber',
    'AI_6b_PartNumber': 'PartNumber',
    'AI_6c_ItemNumber': 'ItemNumber',
    'AI_6d_AdditionalInfo': 'AdditionalInformation',
    'AI_7a_PageNumber': 'PageNumber',
    'AI_7b_PartNumber': 'PartNumber',
    'AI_7c_ItemNumber': 'ItemNumber',
    'AI_7d_AdditionalInfo': 'AdditionalInformation'
}
